### ISSUE TITLE
Preview

### ISSUE THREAD

**Issue by wontaeyang** [pat-whitrock/gitshoes#190]
From: den1k@me.com

Platform: 
MacIntel

Browser: 
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/33.0.1750.152 Safari/537.36

Location: 
/

Message: 
Hey guys, seeing a preview of what it would look like would be nice. If this thing I'm taking in right here is the actual script, then it'd be cool to have that pointed out. As a new user I wouldnt have no idea what this is or how this works or what it will look like.

**Comment by pat-whitrock** [comment]
we should have a 'preview script' button that opens the contents of the script in a modal
