### ISSUE TITLE
This is outdated

### ISSUE THREAD

**Issue by wontaeyang** [pat-whitrock/gitshoes#195]
From: joemburgess@gmail.com

Platform: 
MacIntel

Browser: 
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/33.0.1750.152 Safari/537.36

Location: 
/repos

Message: 
Like 2 years outdated

**Comment by pat-whitrock** [comment]
@wontaeyang do you have any idea this means?

**Comment by wontaeyang** [comment]
hmm... no idea... 
maybe he means idea is outdated?
