### ISSUE TITLE
HTTPS sites

### ISSUE THREAD

**Issue by wontaeyang** [pat-whitrock/gitshoes#196]
From: patrick.whitrock@gmail.com

Platform: 
MacIntel

Browser: 
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/34.0.1847.116 Safari/537.36

Location: 
/repos

Message: 
Widget doesn't work on https://get-xp.herokuapp.com/ on Chrome, but does work on Firefox and Safari.

Error message from console:

[blocked] The page at 'https://get-xp.herokuapp.com/' was loaded over HTTPS, but ran insecure content from 'http://www.gitshoes.com/repos/9.js': this content should also be loaded over HTTPS.

**Comment by pat-whitrock** [comment]
We should look into moving Gitshoes to HTTPS, it might solve this problem.

**Comment by pat-whitrock** [comment]
According to Logan and Arel, this is an anomaly - their site shouldn't be HTTPS. This is something we can tackle at a later date...
