### ISSUE TITLE
Production DB cleared?

### ISSUE THREAD

**Issue by wontaeyang** [pat-whitrock/gitshoes#260]
From: patrick.whitrock@gmail.com

Platform: 
MacIntel

Browser: 
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/34.0.1847.116 Safari/537.36

Location: 
/repos

Message: 
Just logged into production and my repos were gone. I added a repo and it has primary key 1. Did it get wiped when Avi upgraded the Heroku server?

**Comment by pat-whitrock** [comment]
nope, it's fine
