### ISSUE TITLE
Login button

### ISSUE THREAD

**Issue by wontaeyang** [pat-whitrock/gitshoes#280]
From: den1k@me.com

Platform: 
MacIntel

Browser: 
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/34.0.1847.116 Safari/537.36

Location: 
/repos

Message: 
Hi Guys, awesome features. One thing: when I'm about to log in I have to scroll down to the sign in button. Eric says there's a scaling thing you can do to fix that. Test it out w/ your browser window being as wide as possible.

**Comment by pat-whitrock** [comment]
@den1k thanks for the tip. pushed a fix to scale it, it'll be up after our next deployment.
