### ISSUE TITLE
Possible color option?

### ISSUE THREAD

**Issue by wontaeyang** [pat-whitrock/gitshoes#302]
From: cheeseandpepper@gmail.com

Platform: 
MacIntel

Browser: 
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/33.0.1750.152 Safari/537.36

Location: 
/repos

Message: 
Hey guys!

Might it be possible to pick the color theme before the js embed code is generated? Your blue doesn't match our blue so it's just a thought...

**Comment by pat-whitrock** [comment]
This is in development right now, should be deployed tomorrow.

It won't be necessary to regenerate the embed code - you can just save your edits (color, text, etc) to the widget and it will be automatically updated.

**Comment by pat-whitrock** [comment]
@cheeseandpepper this got pushed to production, so you can change your color by visiting your repo on GitShoes and clicking 'Edit'. No need to regenerate or re-embed the script tag afterwards - just hit 'Save widget' when you're done.
