### ISSUE TITLE
You suck!

### ISSUE THREAD

**Issue by wontaeyang** [pat-whitrock/gitshoes#358]
From: david.cheng@lifebooker.com

Platform: 
MacIntel

Browser: 
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_8) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/34.0.1847.131 Safari/537.36

Location: 
/repos

Message: 
Self-evident.

Screenshot: https://s3-us-west-2.amazonaws.com/gitshoes/screenshot20140429-2-1uzd0hy.png

**Comment by wontaeyang** [comment]
thanks for feedback @bdhowald

**Comment by bdhowald** [comment]
Sorry, this wasn't an issue or a complaint.

Patrick was walking me through the app and I was filling in dummy data.
