### ISSUE TITLE
cryptic landing page

### ISSUE THREAD

**Issue by dsernst** [pat-whitrock/gitshoes#367]
A friend pointed me in the direction of www.gitshoes.com. The line "We connect user feedback to your Github repository issues!" seems like a great premise. But there must be more info available?

My only option to learn more is to give you guys complete control over my GitHub account and all repositories?

**Comment by wontaeyang** [comment]
@dsernst Thanks for the feedback. We did not have any time to work on the UX part of the application. As me and Patrick settle down in our new jobs and get more free time, we will get back to making the site better.
